import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class AnalyticsCreate {
  @ApiProperty()
  response_id: string;
  @ApiProperty()
  timestamp: Date;
}

export class Analytics {
  @ApiProperty()
  id: number;
  @ApiProperty()
  response_id: string;
  @ApiProperty()
  timestamp: Date;
}
