import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class SurveyQuestionCreate {
  @ApiProperty()
  survey_id: string;
  @ApiProperty()
  question_id: string;
}

export class SurveyQuestion {
  @ApiProperty()
  id: number;
  @ApiProperty()
  survey_id: string;
  @ApiProperty()
  question_id: string;
}
