/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { SurveyQuestion } from './SurveyQuestion.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { SurveyQuestionService } from './SurveyQuestion.service';
import { SurveyQuestionController } from './SurveyQuestion.controller';

@Module({
  imports: [TypeOrmModule.forFeature([SurveyQuestion])],
  providers: [SurveyQuestionService],
  exports: [SurveyQuestionService],
  controllers: [SurveyQuestionController],
})
export class SurveyQuestionModule {}
