/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import {
  SurveyQuestion,
  SurveyQuestionCreate,
} from './dtos/SurveyQuestion.dto';
import { SurveyQuestionController } from './SurveyQuestion.controller';
import { SurveyQuestionService } from './SurveyQuestion.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('SurveyQuestionController', () => {
  let controller: SurveyQuestionController;
  let spyService: SurveyQuestionService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: SurveyQuestionService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [SurveyQuestionController],
      providers: [SurveyQuestionService, ApiServiceProvider],
    }).compile();

    controller = module.get<SurveyQuestionController>(SurveyQuestionController);
    spyService = module.get<SurveyQuestionService>(SurveyQuestionService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call SurveyQuestionController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call SurveyQuestionController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new SurveyQuestion();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
