/**
 * This file generated by Apso.
 */
import { Controller } from '@nestjs/common';
import {
  Crud,
  CrudController,
  Override,
  ParsedRequest,
  CrudRequest,
  ParsedBody,
  CreateManyDto,
} from '@nestjsx/crud';
import { ApiTags, ApiResponse, ApiOperation, ApiBody } from '@nestjs/swagger';
import {
  SurveyQuestion,
  SurveyQuestionCreate,
} from './dtos/SurveyQuestion.dto';
import { SurveyQuestionService } from './SurveyQuestion.service';

@Crud({
  model: {
    type: SurveyQuestion,
  },
  dto: {
    create: SurveyQuestionCreate,
    update: SurveyQuestion,
    replace: SurveyQuestion,
  },
  query: {
    /**
     * commenting out limit and pagination because of an issue with Crud lib: https://github.com/nestjsx/crud/issues/777
     */
    // TODO: make limit env driven?
    limit: 5,
    alwaysPaginate: true,
  },
})
@Controller('SurveyQuestions')
@ApiTags('SurveyQuestions')
export class SurveyQuestionController
  implements CrudController<SurveyQuestion>
{
  constructor(public service: SurveyQuestionService) {}

  get base(): CrudController<SurveyQuestion> {
    return this;
  }

  @Override('getManyBase')
  @ApiOperation({ summary: 'Retrieve multiple SurveyQuestions' })
  getMany(@ParsedRequest() req: CrudRequest) {
    return this.base.getManyBase(req);
  }

  @Override('getOneBase')
  @ApiOperation({ summary: 'Retrieve a single SurveyQuestion' })
  get(@ParsedRequest() req: CrudRequest) {
    return this.base.getOneBase(req);
  }

  @Override('createOneBase')
  @ApiOperation({ summary: 'Create a single SurveyQuestion' })
  @ApiBody({
    type: SurveyQuestionCreate,
    description:
      'The Description for the Post Body. Please look into the DTO. You will see the @ApiOptionalProperty used to define the Schema.',
  })
  create(@ParsedRequest() req: CrudRequest, @ParsedBody() dto: SurveyQuestion) {
    return this.base.createOneBase(req, dto);
  }

  @Override('createManyBase')
  @ApiOperation({ summary: 'Create multipleSurveyQuestions' })
  createMany(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: CreateManyDto<SurveyQuestion>,
  ) {
    return this.base.createManyBase(req, dto);
  }

  @Override('updateOneBase')
  @ApiOperation({ summary: 'Update a single SurveyQuestion' })
  update(@ParsedRequest() req: CrudRequest, @ParsedBody() dto: SurveyQuestion) {
    return this.base.updateOneBase(req, dto);
  }

  @Override('replaceOneBase')
  @ApiOperation({ summary: 'Replace a single SurveyQuestion' })
  replace(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: SurveyQuestion,
  ) {
    return this.base.replaceOneBase(req, dto);
  }

  @Override('deleteOneBase')
  @ApiOperation({ summary: 'Delete a single SurveyQuestion' })
  delete(@ParsedRequest() req: CrudRequest) {
    return this.base.deleteOneBase(req);
  }
}
